name: Auto Deploy to cPanel

on:
  push:
    branches:
      - main # jalankan otomatis saat kamu push ke branch main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync files to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.CPANEL_FTP_SERVER }}
          username: ${{ secrets.CPANEL_FTP_USERNAME }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          server-dir: ${{ secrets.CPANEL_FTP_DIR }}
          # local-dir: ./ # folder lokal project
          exclude: |
            */.git
            */.github
            */node_modules/*
            */vendor/*
            **/.env
